package view;

import dao.NotificationDAO;
import dao.PatientDAO;
import model.Notification;
import model.Patient;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.util.List;

public class Notificationview extends JFrame {
    private JPanel mainPanel;
    private JComboBox<String> patientCombo;
    private JButton viewButton;
    private JTable notificationTable;

    private NotificationDAO notificationDAO = new NotificationDAO();
    private PatientDAO patientDAO = new PatientDAO();

    public Notificationview() {
        setTitle("Patient Notifications");
        setSize(700, 500);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setContentPane(mainPanel); // Add this line!
        setLocationRelativeTo(null);

        // Initialize table
        initializeTable();

        loadPatients();

        // Action Listener
        viewButton.addActionListener(e -> viewNotifications());
    }

    private void initializeTable() {
        String[] columns = {"ID", "Message", "Date", "Sent"};
        DefaultTableModel model = new DefaultTableModel(columns, 0);
        notificationTable.setModel(model);
    }

    private void loadPatients() {
        patientCombo.removeAllItems();
        try {
            List<Patient> patients = patientDAO.getAllPatients();
            if (patients.isEmpty()) {
                patientCombo.addItem("No patients available");
            } else {
                for (Patient p : patients) {
                    patientCombo.addItem(p.getId() + " - " + p.getName());
                }
            }
        } catch (Exception e) {
            patientCombo.addItem("Error loading patients");
            JOptionPane.showMessageDialog(this, "Error loading patients: " + e.getMessage());
        }
    }

    private void viewNotifications() {
        try {
            String patientStr = (String) patientCombo.getSelectedItem();

            if (patientStr == null || patientStr.equals("No patients available")) {
                JOptionPane.showMessageDialog(this, "Please add patients first");
                return;
            }

            int patientId = Integer.parseInt(patientStr.split(" - ")[0]);

            DefaultTableModel model = (DefaultTableModel) notificationTable.getModel();
            model.setRowCount(0);

            List<Notification> notifications = notificationDAO.getNotificationsByPatient(patientId);

            if (notifications.isEmpty()) {
                JOptionPane.showMessageDialog(this, "No notifications found for this patient");
            }

            for (Notification n : notifications) {
                model.addRow(new Object[]{
                        n.getId(),
                        n.getMessage(),
                        n.getDate(),
                        n.isSent() ? "Yes" : "No"
                });
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
            ex.printStackTrace();
        }
    }

    private void initUI() {
        mainPanel = new JPanel(new BorderLayout(10, 10));
        mainPanel.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10));
        setContentPane(mainPanel);

        // Input Panel
        JPanel inputPanel = new JPanel(new FlowLayout(FlowLayout.LEFT));
        inputPanel.add(new JLabel("Patient:"));
        patientCombo = new JComboBox<>();
        inputPanel.add(patientCombo);
        viewButton = new JButton("View Notifications");
        inputPanel.add(viewButton);

        mainPanel.add(inputPanel, BorderLayout.NORTH);

        // Table
        notificationTable = new JTable();
        mainPanel.add(new JScrollPane(notificationTable), BorderLayout.CENTER);
    }

    {
        initUI();
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(4, 2, new Insets(0, 0, 0, 0), -1, -1));
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        panel1.add(panel2, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 2, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        final com.intellij.uiDesigner.core.Spacer spacer1 = new com.intellij.uiDesigner.core.Spacer();
        panel1.add(spacer1, new com.intellij.uiDesigner.core.GridConstraints(2, 1, 2, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_VERTICAL, 1, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        patientCombo = new JComboBox();
        panel1.add(patientCombo, new com.intellij.uiDesigner.core.GridConstraints(2, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        viewButton = new JButton();
        viewButton.setText("View");
        panel1.add(viewButton, new com.intellij.uiDesigner.core.GridConstraints(3, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        notificationTable = new JTable();
        panel1.add(notificationTable, new com.intellij.uiDesigner.core.GridConstraints(1, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(150, 50), null, 0, false));
    }
}
