package view;

import dao.ReportDAO;

import javax.swing.*;
import java.awt.*;
import java.util.Map;

public class Reportview extends JFrame {
    private JPanel mainPanel;
    private JTextField monthField;
    private JButton generateButton;
    private JTextArea reportArea;

    private ReportDAO reportDAO = new ReportDAO();

    public Reportview() {
        setTitle("Monthly Reports");
        setSize(700, 500);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setContentPane(mainPanel); // Add this line!
        setLocationRelativeTo(null);

        // Set report area properties
        reportArea.setEditable(false);
        reportArea.setFont(new Font("Monospaced", Font.PLAIN, 12));

        // Action Listener
        generateButton.addActionListener(e -> generateReport());
    }

    private void generateReport() {
        try {
            String month = monthField.getText().trim();

            if (month.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please enter a month (YYYY-MM)");
                return;
            }

            StringBuilder report = new StringBuilder();
            report.append("========================================\n");
            report.append("     MONTHLY REPORT FOR ").append(month).append("\n");
            report.append("========================================\n\n");

            // Appointment Volume
            report.append("1. APPOINTMENT VOLUMES:\n");
            report.append("   ----------------------------\n");
            Map<String, Integer> volumes = reportDAO.getMonthlyAppointmentVolume(month);
            if (volumes.isEmpty()) {
                report.append("   No appointments found.\n");
            } else {
                for (Map.Entry<String, Integer> entry : volumes.entrySet()) {
                    report.append(String.format("   %-15s: %d\n", entry.getKey(), entry.getValue()));
                }
            }
            report.append("\n");

            // Doctor Performance
            report.append("2. DOCTOR PERFORMANCE:\n");
            report.append("   ----------------------------\n");
            Map<String, Integer> performance = reportDAO.getDoctorPerformance(month);
            if (performance.isEmpty()) {
                report.append("   No completed appointments found.\n");
            } else {
                for (Map.Entry<String, Integer> entry : performance.entrySet()) {
                    report.append(String.format("   %-20s: %d completed\n", entry.getKey(), entry.getValue()));
                }
            }
            report.append("\n");

            // Patient Visits
            report.append("3. PATIENT VISITS:\n");
            report.append("   ----------------------------\n");
            int visits = reportDAO.getPatientVisits(month);
            report.append(String.format("   Unique Patients: %d\n", visits));

            report.append("\n========================================\n");

            reportArea.setText(report.toString());

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
            ex.printStackTrace();
        }
    }

    private void initUI() {
        mainPanel = new JPanel(new BorderLayout(10, 10));
        mainPanel.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10));
        setContentPane(mainPanel);

        // Input Panel
        JPanel inputPanel = new JPanel(new FlowLayout(FlowLayout.LEFT));
        inputPanel.add(new JLabel("Month (YYYY-MM):"));
        monthField = new JTextField(10);
        inputPanel.add(monthField);
        generateButton = new JButton("Generate Report");
        inputPanel.add(generateButton);

        mainPanel.add(inputPanel, BorderLayout.NORTH);

        // Report Area
        reportArea = new JTextArea();
        reportArea.setEditable(false);
        reportArea.setFont(new Font("Monospaced", Font.PLAIN, 12));
        mainPanel.add(new JScrollPane(reportArea), BorderLayout.CENTER);
    }

    {
        initUI();
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(5, 1, new Insets(0, 0, 0, 0), -1, -1));
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        panel1.add(panel2, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        final com.intellij.uiDesigner.core.Spacer spacer1 = new com.intellij.uiDesigner.core.Spacer();
        panel1.add(spacer1, new com.intellij.uiDesigner.core.GridConstraints(4, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_VERTICAL, 1, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        monthField = new JTextField();
        panel1.add(monthField, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        generateButton = new JButton();
        generateButton.setText("Generate Report");
        panel1.add(generateButton, new com.intellij.uiDesigner.core.GridConstraints(2, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        reportArea = new JTextArea();
        panel1.add(reportArea, new com.intellij.uiDesigner.core.GridConstraints(3, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(150, 50), null, 0, false));
    }
}
